import { config } from "dotenv";

config();

const configs = {
  GOOGLE_API: process.env.REACT_APP_GOOGLE_MAPS_API,
  USERNAME: process.env.REACT_APP_USERNAME,
  PASSWORD: process.env.REACT_APP_PASSWORD,
  CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
  GRANT_TYPE: process.env.REACT_APP_GRANT_TYPE,
  CLIENT_SECRET: process.env.REACT_APP_CLIENT_SECRET,
  FALL_BACK_ENDPOINT: process.env.REACT_APP_FALL_BACK_ENDPOINT,
  FALL_BACK_ENDPOINT_HIRE: process.env.REACT_APP_FALL_BACK_ENDPOINT_HIRE,
  FALL_BACK_ENDPOINT_WOVEN: process.env.REACT_APP_FALL_BACK_ENDPOINT_WOVEN,
  FALL_BACK_ENDPOINT_FLUTTER: process.env.REACT_APP_FALL_BACK_ENDPOINT_FLUTTER,
  FALL_BACK_ENDPOINT_FUND_WALLET:process.env.REACT_APP_FALL_BACK_ENDPOINT_FUND_WALLET,
  FALL_BACK_ENDPOINT_WOVEN_WALLET:process.env.REACT_APP_FALL_BACK_ENDPOINT_FUND_WALLET_WOVEN,
};

export default configs;
